gopala3/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path

from yogam.views import index


urlpatterns = [
    path('yogam/', include('yogam.urls')),
    path('', index, name='index'),
    path('accounts/login/',
         LoginView.as_view(template_name='yogam/login.html'), name="login"),
    path('accounts/logout/',
         LogoutView.as_view(template_name='yogam/index.html'), name="logout"),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yogam/urls.py
from django.urls import path


from . import views


app_name = 'yogam'
urlpatterns = [
    path('news_list/', views.news_list, name='news-list'),
    path('news/<int:pk>/', views.NewsDetailView.as_view(), name='news'),
    path('articles/', views.articles, name='articles'),
    path('article/<int:id>/', views.article, name='article'),
    path('photos/<int:id>/', views.photos, name='photos'),
    path('tree/', views.tree, name='tree'),
    path('get_member_data/', views.get_member_data, name='member-data'),
    path('births/<str:month>/', views.births, name='births'),
    path('members/', views.MembersView.as_view(), name='members'),
    path('blood_groups/', views.blood_groups, name='blood_groups'),
    path('member_list/', views.MemberList.as_view(), name='member-list'),
    path('committee/', views.committee, name='committee'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('feedback/', views.feedback, name='feedback'),
    path('family/<int:id>/', views.family, name='family'),
    path('messages/', views.messages, name='messages'),
    path('name_search/', views.name_search, name='name-search'),
]

yogam/forms.py
from django import forms

from .models import NewsItem, Feedback


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = '__all__'
        exclude = ['reply']


class NewsForm(forms.ModelForm):
    class Meta:
        model = NewsItem
        fields = '__all__'
        exclude = ['is_public', 'pic_width', 'pic_height']

yogam/views.py
import datetime
from cgi import escape

from django.db.models import Q
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render
from django.template import loader
from django.template import Context
from django.template.loader import get_template
from django.contrib.gis.geoip2 import GeoIP2
from django.views import View
from django.views.generic import TemplateView, ListView
from django.views.generic.detail import DetailView

from .forms import NewsForm, FeedbackForm
from .models import NewsItem as News
from .models import Article, ArticlePhoto, Member, MONTH_LIST, Feedback, \
    NewsItem, Accessed_IP, Banner


# recursively generate the tree from a root
def make_tree(root):
    children = root.children()
    child_list = []
    if children.count():
        for child in children:
            tree = make_tree(child)
            child_list.append(tree)
    return {root: child_list}


# handle any attachments from the news form or feedback form
def handle_uploaded_file(f):
    destination = open(settings.MEDIA_ROOT + f.name, 'wb+')
    for chunk in f.chunks():
        destination.write(chunk)
    return


# try to get the ip of the client
def get_client_ip(request):
    ip = ''
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR', None)
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR', '')
    return ip


# update the last accessed date of an ip existing in the database
def update_ip(request):
    accessed_ip = None
    today = datetime.date.today()
    ip = get_client_ip(request)
    if ip:
        g = GeoIP2()
        city = None
        try:
            city = g.city(ip)
        except Exception as e:
            pass

        accessed_ips = Accessed_IP.objects.filter(ip=ip)

        location = ''
        if city is not None:
            location = ''
            if 'city' in city and city['city'] is not None:
                location += city['city']
            if 'region' in city and city['region'] is not None:
                location += ' ' + city['region']
            if 'country_name' in city and city['country_name'] is not None:
                location += ' ' + city['country_name']

        if accessed_ips.count():
            accessed_ip = accessed_ips[0]
            if accessed_ip.last_date != today:
                accessed_ip.last_date = today
                accessed_ip.city = location
                accessed_ip.save()
        else:
            accessed_ip = Accessed_IP(ip=ip, city=location)
            accessed_ip.save()
    return accessed_ip


def index(request):
    accessed_ip = update_ip(request)
    home_articles = Article.objects.filter(home_page=True)\
        .values('title', 'id')
    context = {'articles': articles, 'accessed_ip': accessed_ip}
    today = datetime.date.today()
    members = Member.objects.filter(date_of_birth=today)
    if members.count():
        context['members'] = members
    banners = Banner.objects.all().order_by('-id')
    if banners.count():
        context['banner'] = banners[0]
    return render(request, 'yogam/index.html', context)


class AboutView(TemplateView):
    template_name = "yogam/about.html"


# printable member list
class MemberList(ListView):
    model = Member


# the members list page
class MembersView(View):
    template_name = "yogam/members.html"

    def get(self, request):
        members = Member.objects.all().order_by('nick_name')\
            .values('nick_name', 'contact_number', 'icon', 'name', 'job',
                    'role', 'address', 'official_address', 'email')

        alpha = []
        for m in members:
            letter = m['nick_name'][0].lower()
            if letter not in alpha:
                alpha.append(letter)

        context = {'members': members, 'letters': alpha}
        return render(request, self.template_name, context)


def news_list(request):
    accessed_ip = update_ip(request)
    message = ''
    error = ''
    form = NewsForm()
    if request.method == 'POST':
        form = NewsForm(request.POST, request.FILES)
        message = 'News not saved.'
        error = True
        if form.is_valid():
            form.save()
            message = 'News saved.'
            error = False
            try:
                picture = request.FILES['picture']
                handle_uploaded_file(picture)
            except Exception as e:
                pass
            form = NewsForm()
    news = News.objects.filter(is_public=True).order_by('-event_date')
    context = {'news_list': news, 'form': form, 'message': message,
               'error': error, 'accessed_ip': accessed_ip}
    return render(request, 'yogam/news_list.html', context)


class NewsDetailView(DetailView):
    model = News


def messages(request):
    messages = Feedback.objects.order_by('-id')
    context = {'messages': messages}
    return render(request, 'yogam/messages.html', context)


def articles(request):
    articles = Article.objects.filter(is_public=True).exclude(home_page=True)\
        .order_by('-published_date')
    context = {'articles': articles}
    return render(request, 'yogam/articles.html', context)


@login_required
def article(request, id=None):
    article = Article.objects.get(pk=id)
    context = {'article': article}
    template = 'yogam/article.html'
    count = article.photo_count()
    if count:
        template = 'yogam/album.html'
        photo = ArticlePhoto.objects.filter(article_id=id).order_by('id')[0]
        context['photo'] = photo
        context['photos'] = ArticlePhoto.objects.filter(article_id=id)\
            .order_by('id').values('picture', 'id')
    return render(request, template, context)


def photos(request, photo_id=None):
    next = request.GET.get('next', None)
    prev = request.GET.get('prev', None)
    photo = ArticlePhoto.objects.get(pk=photo_id)
    photo1 = None
    try:
        if prev:
            photo1 = ArticlePhoto.objects.filter(article=photo.article)\
                .order_by('id').filter(id__lt=photo_id).last()
        elif next:
            photo1 = ArticlePhoto.objects.filter(article=photo.article)\
                .order_by('id').filter(id__gt=photo_id).first()
    except Exception as e:
        pass
    if photo1:
        photo = photo1
    article = photo.article
    context = {'photo': photo, 'article': article}
    return render(request, 'yogam/album.html', context)


@login_required
def get_photo(request):
    next = request.GET.get('next', None)
    prev = request.GET.get('prev', None)
    photo_id = request.GET.get('photo_id', None)
    photo = ArticlePhoto.objects.get(pk=photo_id)
    photo1 = None
    try:
        if prev:
            photo1 = ArticlePhoto.objects.filter(article=photo.article)\
                .order_by('id').filter(id__lt=photo_id).last()
        elif next:
            photo1 = ArticlePhoto.objects.filter(article=photo.article)\
                .order_by('id').filter(id__gt=photo_id).first()
    except Exception as e:
        pass
    if photo1:
        photo = photo1
    article = photo.article
    context = {'photo': photo, 'article': article}
    return render(request, 'yogam/album.html', context)


# recursively traverse a tree and render it in html
def traverse_tree(child_list):
    html = ''
    if len(child_list):
        for child_dict in child_list:
            member = child_dict.keys()[0]
            div = ''
            member_generation = member.generation
            generation = member_generation - 1
            margin = generation * 10

            if member_generation > 2:
                div += '<div class="node-row %s" style="display:none;">' % \
                       member.parent_ids()
            else:
                div += '<div class="node-row %s">' % member.parent_ids()

            i = 1
            while i < member_generation:
                if member.is_youngest():
                    if i == member_generation - 2 \
                            and member.parent.is_youngest() \
                            or i == member_generation - 3 \
                            and member.parent.parent.is_youngest():
                        div += '<span class="node-connector gen" ' \
                               'style="margin-left:20px;"></span>'
                    else:
                        div += '<span class="node-connector" ' \
                               'style="margin-left:20px;"></span>'
                else:
                    if i == member_generation - 2 \
                            and member.parent.is_youngest() \
                            or i == member_generation - 3 \
                            and member.parent.parent.is_youngest():
                        div += '<span class="node-connector gen" ' \
                               'style="margin-left:20px;"></span>'
                    else:
                        div += '<span class="node-connector" ' \
                               'style="margin-left:20px;"></span>'
                i += 1

            div += '<span class ="gen%s-conn">&nbsp;</span>' % \
                   member_generation

            div += '<span class="node-container">'

            div += '<span class="node-span">'
            div += '<span class="gen%s">' % member_generation

            if member_generation == 2:
                div += '<span class="toggle" id="%s">' % \
                       member.id + member.nick_name + '</span>'
            else:
                div += member.nick_name

            div += ' <img id="%s" class="memberimg" title="%s" ' \
                   'style="width:20px;" src="%s" alt="pic">' % \
                   (member.id, member.nick_name, member.icon.url)
            div += '</span>'
            div += '</span>'

            spouse = member.spouse
            if spouse:
                div += '<span class="node-span">'

yogam/templates/yogam/album.html
{% extends "yogam/base.html" %}
{% load static %}

{% block extrahead %}
    <title>GVKY | {{ article.title }}</title>
{% endblock %}

{% block content %}

    <a href="{% url 'yogam:articles' %}">
        <div id="back2list"> <img src="{% static 'images/icons-png/back-black.png' %}"> Back to List</div>
    </a>

    <div class="page-title">{{ article.title }}</div>
    <div class="article-title">{{ article.author }}</div>

    <div class="gallerybox">
        Touch any photo to begin the slideshow.<br>
        Swipe left or right to move through the slideshow.

        <div id="links">
            {% for ph in photos %}
                <a href="/media/{{ ph.picture }}" title="{{ article.title }} - {{ forloop.counter }}" data-gallery>
                    <img src="/media/{{ ph.picture }}" alt="{{ article.title }} - {{ forloop.counter }}" height="80px">
                </a>
            {% endfor %}
        </div>
    </div>

{% endblock %}

{% block slider %}
    <div id="blueimp-gallery" class="blueimp-gallery" data-use-bootstrap-modal="false">
        <!-- The container for the modal slides -->
        <div class="slides"></div>
        <!-- Controls for the borderless lightbox -->
        <h3 class="title"></h3>
        <a class="prev">‹</a>
        <a class="next">›</a>
        <a class="close">×</a>
        <a class="play-pause"></a>
        <ol class="indicator"></ol>
        <!-- The modal dialog, which will be used to wrap the lightbox content -->
        <div class="modal fade">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" aria-hidden="true">&times;</button>
                        <h4 class="modal-title"></h4>
                    </div>
                    <div class="modal-body next"></div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default pull-left prev">
                            <i class="glyphicon glyphicon-chevron-left"></i>
                            Previous
                        </button>
                        <button type="button" class="btn btn-primary next">
                            Next
                            <i class="glyphicon glyphicon-chevron-right"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block sliderbottom %}
    <script src="{% static 'js/jquery.blueimp-gallery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-image-gallery.min.js' %}"></script>
{% endblock %}

{% block bottom-link %}
    {% if not article.home_page %}
        <a href="{% url 'yogam:articles' %}"><div class="back-link">Back to Albums</div></a>
    {% endif %}
{% endblock %}

yogam/templates/yogam/article.html
{% extends "yogam/base.html" %}
{% load static %}
{% block content %}
    <a href="{% url 'yogam:articles' %}">
        <div id="back2list"> <img src="{% static 'images/icons-png/back-black.png' %}"> Back to List</div>
    </a>
    <div class="page-title">{{ article.title }}</div>
    <div class="newsbox">
        <p class="newsbody">
            {% if article.picture %}
                <img src="{{ article.picture.url }}" width="200px" alt="{{ article.picture.url }}"/><br>
            {% endif %}
            {{ article.body|safe }}
        </p>
    </div>
{% endblock %}

{% block bottom-link %}
    {% if not article.home_page %}
        <a href="{% url 'yogam:articles' %}"><div class="back-link">Back to Albums</div></a>
    {% endif %}
{% endblock %}

yogam/templates/yogam/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="{% static 'images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon"/>

        <meta property="og:title" content="GOPALAVILASAM" />
        <meta property="og:url" content="http://www.gopalavilasam.com/" />
        <meta property="og:description" content="Welcome to our Kudumbayogam" />
        <meta property="og:image" content="http://www.gopalavilasam.com/static/images/logo5.png" />
        <meta property="og:type" content="article" />

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <!-- jQuery library -->
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <!-- Latest compiled JavaScript -->
        <script src="{% static 'js/bootstrap.min.js' %}"></script>

        <link rel="stylesheet" type="text/css" href="{% static 'css/styles_30.css' %}"/>
        <script type="text/javascript" src="{% static 'js/util.js' %}"></script>

        <link rel="stylesheet" href="{% static 'css/blueimp-gallery.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-image-gallery.min.css' %}">

        {% block extrahead %}
        {% endblock %}

        {% block title %}
        {% endblock %}

    </head>
    <body>
        {% block slider %}{% endblock %}

        <div class="container-fluid outerfluid">
            <nav class="navbar navbar-default">
                <div class="container-fluid innerfluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-left" href="/">
                            <span id="brand">gopalavilasam</span>
                        </a>
                    </div>
                    <div class="collapse navbar-collapse" id="myNavbar">
                        <ul class="nav navbar-nav">
                            <li><a href="/">Home</a></li>
                            <li><a href="{% url 'yogam:tree' %}">Tree</a></li>
                            <li><a href="{% url 'yogam:members' %}">Members</a></li>
                            <li><a href="{% url 'yogam:births' 'init' %}">Birthdays</a></li>
                            <li><a href="{% url 'yogam:news-list' %}">News</a></li>
                            <li><a href="{% url 'yogam:articles' %}">Albums</a></li>
                            {% for article in home_articles %}
                                <li><a href="{% url 'yogam:article' article.id %}">{{ article.title }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </nav>
            <div id="content">
                {% block content%}{% endblock %}
            </div>
        </div>

        <div id="base">
            {% block bottom-link %}{% endblock %}
        </div>

        <div style="clear:both;"></div>

        <div id="footer">
            {% block footer%}
                <div class="footerdiv">
                    <img src="/static/images/logo5.png"><br>
                    <a href="{% url 'yogam:feedback' %}" class="link bold">Feedback</a>
                    &#9900; <a href="{% url 'yogam:messages' %}" class="link bold">Messages</a>
                    &#9900; <a href="{% url 'yogam:committee' %}" class="link bold">Committee</a>
                    &#9900; <a href="{% url 'yogam:about' %}" class="link bold">About</a>
                    {% if user.is_authenticated %}
                        &#9900; <a href="{% url 'logout' %}?next=/" class="link bold">Logout</a>
                    {% else %}
                        &#9900; <a href="{% url 'login' %}?next=/" class="link bold">Login</a>
                    {% endif %}
                    <br><br> Gopalavilasam Kudumbayogam
                    <br>Alapra Kerala India
                    <br>gopalavilasam@gmail.com
                    {% if accessed_ip %}
                        <br><br>{% if accessed_ip.city %} You visit from: {{ accessed_ip.city }} {% endif %}
                    {% endif %}
                </div>
            {% endblock %}
            <br>
        </div>
        <div id="loader" style="display:none;"><img style="width:50px;" src="/static/images/grey.gif"></div>

        {% block sliderbottom %}{% endblock %}

    </body>
</html>

yogam/templates/yogam/births.html
{% extends "yogam/base.html" %}

{% block content %}
    <div class="page-title">Birthdays {{current_year}}</div>

    <div class="alpha">
        {% for k,v in months.items %}
            <a href="{% url 'yogam:births' k %}">
                <span class="month-link {% if selected == k %}selected{% else %}{% if k == current_month %} current-month {% endif %}{% endif %}">
                    {{v|date:"M"}}
                </span>
            </a>
        {% endfor %}
        <a href="{% url 'yogam:births' 'all' %}">
            <span class="month-link {% if selected == 'all' %}selected{% endif%}">All</span>
        </a>
    </div>

    {% if calendar %}
        <table id="calendar">
            <tr>
                <td colspan="7">{{ start|date:"M Y" }}</td>
            </tr>
            <tr>
                <td class="cal-day cal-weekday">SUN</td>
                <td class="cal-day cal-weekday">MON</td>
                <td class="cal-day cal-weekday">TUE</td>
                <td class="cal-day cal-weekday">WED</td>
                <td class="cal-day cal-weekday">THU</td>
                <td class="cal-day cal-weekday">FRI</td>
                <td class="cal-day cal-weekday">SAT</td>
            </tr>
            <tr>
                {% for day, members in calendar %}
                    {% if forloop.counter == 1 %}
                        {% for i in empty_days %}
                            <td class="cal-empty"></td>
                        {% endfor %}
                    {% endif %}
                    <td class="cal-day">
                        {{ day|date:"d" }}
                        {% for member in members %}
                            <div class=cal-mem>
                                <img src="/media/{{ member.icon }}" width="40px;">
                                <br>{{ member.nick_name }}
                            </div>
                        {% endfor %}
                    </td>
                    {% if day.weekday == 5 %}
                        </tr><tr>
                    {% endif %}
                {% endfor %}
            </tr>
        </table>
    {% else %}

        All Birthdays

        <table id="dob">
            {% regroup members by dob_monthname as grouped %}
            {% for group in grouped %}
                <tr>
                    <td colspan="3" class="month {% if current_month == group.grouper %}current-month{% endif %}">
                        {{ group.grouper }}
                    </td>
                </tr>
                {% for member in group.list %}
                    <tr>
                        <td class="dob-day {% if current_month == group.grouper %}current-month{% endif %}">
                            {{ member.date_of_birth|date:"d" }}
                        </td>
                        <td class="dob-name {% if current_month == group.grouper %}current-month{% endif %}">
                            <img src="/media/{{ member.icon }}"><br>
                            <span class="bold">{{ member.nick_name }}</span><br>
                            <span class="small">{{ member.name }}</span>
                        </td>
                    </tr>
                {% endfor %}
            {% endfor %}
        </table>
    {% endif %}
    <div>&nbsp;</div>
{% endblock %}

yogam/templates/yogam/blood.html
{{blood|safe}}

yogam/templates/yogam/member_data.html
{% if member.picture  %}
    <img id="member_image" src="{{ member.picture.url }}" style="width:100px; display:none;">
{% endif %}
<div>{{ member.name }}</div>

<div class="other-details">
    <table>
        {% if member.job %}
            <tr>
                <td>Occupation</td>
                <td class="bold">{{ member.job }}</td>
            </tr>
        {% endif %}
        {% if member.date_of_birth %}
            <tr>
                <td>Born on</td>
                <td class="bold">{{ member.date_of_birth|date:"F j, Y (l)" }}</td>
            </tr>
        {% endif %}
        {% if member.birth_star or member.birth_month %}
            <tr>
                <td>പിറന്നാൾ</td>
                <td class="bold">
                    {% if member.birth_star %}{{ member.malayalam_star }}{% endif %}
                    {% if member.birth_month %} ({{ member.malayalam_month }}){% endif %}
                </td>
            </div>
        {% endif %}
        {% if user.is_authenticated %}
            {% if member.contact_number %}
                <tr>
                    <td>Contact Number</td>
                    <td class="bold">{{ member.contact_number }}</td>
                </tr>
            {% endif %}
            {% if member.email %}
                <tr>
                    <td>Email</td>
                    <td class="bold">{{ member.email }}</td>
                </tr>
            {% endif %}
            {% if member.address %}
                <tr>
                    <td>Address</td>
                    <td class="bold">{{ member.address|safe }}</td>
                </tr>
            {% endif %}
            {% if member.official_address %}
                <tr>
                    <td>Office</td>
                    <td class="bold">{{ member.official_address|safe }}</td>
                </tr>
            {% endif %}
        {% endif %}
        {% if member.blood_group %}
            <tr>
                <td>Blood Group</td>
                <td class="bold">{{ member.blood_group }}</td>
            </tr>
        {% endif %}
        {% with member.children as children %}
            {% if children %}
                <tr>
                    <td>Children</td>
                    <td class="bold">
                        {% for c in children %}
                            {{ c.name }}<br>
                        {% endfor %}
                    </td>
                </tr>
                {% if member.parent %}
                    <tr>
                        <td></td>
                        <td class="bold">
                            <a href="{% url 'yogam:family' member.id %}" target="_blank">Family >></a>
                        </td>
                    </tr>
                {% endif %}
            {% endif %}
        {% endwith %}

    </table>
</div>

yogam/templates/yogam/members.html
{% extends "yogam/base.html" %}
{% load static %}

{% block extrahead %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/members.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="page-title">Members</div>
    
    <div class="alpha">
        {% for letter in letters %}
            <span id={{letter}} class="alpha-link">{{letter|upper}}</span>
        {% endfor %}
        <span class="alpha-link">All</span>
    </div>

    <table id="members" cellspacing="10">
        {% for member in members %}
            <tr>
                <td class="con-td center" style="text-align:center;">
                    <input class="keys1" type="hidden" value="{{member.nick_name|lower}}">
                    <input class="keys2" type="hidden" value="{{member.name|lower}}">
                    <img src="/media/{{ member.icon }}"><br>
                    {{ member.nick_name }}<br>
                    <div class="role">{{member.name}}</div>
                    {% if member.role %}
                        <div class="role">({{ member.role }} GVKY)</div>
                    {% endif %}
                </td>
                <td class="con-td">
                    {% if user.is_authenticated %}
                        {% if member.contact_number %}
                            <div class="address">{{ member.contact_number }}</div>
                        {% endif %}

                        {% if member.email %}
                            <div class="address">{{ member.email }}</div>
                        {% endif %}
                        {% if member.address %}
                            <div class="address">{{ member.address|safe }}</div>
                        {% endif %}
                    {% endif %}
                    {% if member.blood_group %}
                        <div class="address">Blood Group: {{ member.blood_group }}</div>
                    {% endif %}
                    {% if member.job %}
                        <div class="address">{{ member.job }}</div>
                    {% endif %}
                    {% if member.official_address %}
                        <div class="address">{{ member.official_address|safe }}</div>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

{% block bottom-link %}
    <div class="back-link">
        <a href="{% url 'yogam:blood_groups' %}">Blood Groups</a>
        {% if user.is_authenticated %}
             | <a href="{% url 'yogam:member-list' %}" target="_blank">Printable List</a>
        {% endif %}
    </div>
{% endblock %}

yogam/templates/yogam/news_list.html
{% extends "yogam/base.html" %}
{% load static %}

{% block extrahead %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
    <link type="text/css" href="{% static 'js/jquery-ui.min.css' %}" rel="stylesheet"/>
    <script type="text/javascript" src="{% static 'js/news_list.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/name_search.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="page-title">News</div>
    <div id="add_row" {% if error %} style="display:none;" {% endif %}>
        {% if user.is_authenticated %}
            <span id="add_button">Add News</span>
        {% endif %}
        <span>{{message}}</span>
    </div>
    <div {% if not error %} style="display:none;" {% endif %} id="add_form">
        <form method="post" enctype="multipart/form-data" action=".">
            {% csrf_token %}
            <table class="small full">
                <tr>
                    <th>Add News</th>
                    <td class="right"><span id="add_close">Close</span></td>
                </tr>
                {{form.as_table}}
                <tr>
                    <td></td>
                    <td class="right"><input type="submit" value="Save"></td>
                </tr>
            </table>
        </form>
    </div>
    {% for news in news_list %}
        <a href="{% url 'yogam:news' news.id %}">
            <div class="news-list-item">{{ news.title }}</div>
        </a>
    {% endfor %}
    <div class="newsbox">
        <p class="newsbody">
            {% if user.is_authenticated %}
                If you have a news to publish, please use the Add News button above the news list.
            {% else %}
                If you have a news to publish, please Login to add it.<br   >
                You will see the Add News button above the news list, when you get logged in.
            {% endif %}
        </p>
    </div>
    <div id="popup" style="display:none;">
        <div id="popup_body"></div>
    </div>
{% endblock %}